"""Add decision count

Revision ID: 342e9c3aafb6
Revises: b0c7df6ad8d7
Create Date: 2026-01-01 11:08:00.519490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342e9c3aafb6'
down_revision: Union[str, None] = 'b0c7df6ad8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('decision_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'decision_count')
    # ### end Alembic commands ###
