"""Add observability columns

Revision ID: b0c7df6ad8d7
Revises: 72039d74e4e6
Create Date: 2026-01-01 10:59:24.392196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c7df6ad8d7'
down_revision: Union[str, None] = '72039d74e4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('execution_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'execution_time')
    op.drop_column('messages', 'token_count')
    # ### end Alembic commands ###
